services:
  app:
    container_name: webscrapingautomatic-dev
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app:cached
      - /app/node_modules # evita compartir node_modules con host
    ports:
      - 3000:3000
    command: sh -c "npm install && npm run dev"
